# Generated by Django 3.2.8 on 2022-02-23 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20220223_1501'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee_name',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='name', to='manager.employee'),
        ),
    ]
